version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    restart: always
    networks:
      - expense-nw
    volumes:
      - ./mydb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pTest@123"]
      interval: 6s
      timeout: 5s
      retries: 3

  mainapp:
    container_name: expensesapp
    build:
      context: .
    ports:
      - "8080:8080"
    restart: always
    networks:
      - expense-nw
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8080/admin || exit 1"]
      interval: 5s
      timeout: 6s
      retries: 3
    depends_on:
      - mysql
    environment:
      spring_datasource_url: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      spring_datasource_username: root
      spring_datasource_password: Test@123

networks:
  expense-nw:
    driver: bridge
volumes:
  mydb-data:
